# - name: Cache Playwright Browsers
#   uses: actions/cache@v3
#   with:
#     path: ~/.cache/ms-playwright
#     key: ${{ runner.os }}-playwright
#     restore-keys: |
#       ${{ runner.os }}-playwright
