# name: Deploy to Vercel

# on:
#   push:
#     branches:
#       - main # 监听主分支

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       # 检出代码
#       - name: Checkout code
#         uses: actions/checkout@v3

#       # 设置 Node.js 环境
#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: "22" # 确保版本与本地一致
#           cache: "npm"

#       # 安装依赖
#       - name: Install dependencies
#         run: npm install

#       # 安装 Playwright 依赖
#       - name: Install Playwright
#         run: npm install -D @playwright/test@latest
#       # 安装 Playwright 依赖
#       - name: Install Playwright-browser
#         run: npx playwright install --with-deps

#       # 构建 Astro 项目
#       - name: Build project
#         run: npm run build

#       - name: Install Vercel CLI
#         run: npm install -g vercel

#       - name: link Vercel CLI
#         run: vercel link --token ${{ secrets.VERCEL_TOKEN }} --yes
#       - name: Deploy to Vercel
#         env:
#           VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
#         run: vercel deploy ./dist --prod --token ${{ secrets.VERCEL_TOKEN }} --yes
